#!/usr/bin/env bash
# 22-harbor-robot.sh — create a least-privilege Harbor ROBOT ACCOUNT for CI (push+pull scoped to
# the two mirror projects), so the pipeline authenticates as a robot instead of `admin`.
#
# Runs on the dual-homed jump box against the lab (or the local KinD) Harbor, using the CURRENT
# HARBOR_USERNAME/HARBOR_PASSWORD (admin) to mint the robot. Harbor shows a robot's secret ONCE at
# creation, so this writes the robot name + secret to a gitignored 0600 file for you to copy into
# .env — the secret is NEVER printed to stdout or passed on argv.
#
# Usage: HARBOR_ROBOT_NAME=<name> scripts/22-harbor-robot.sh   (name defaults to vks-cicd)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/os.sh
. "${SCRIPT_DIR}/lib/os.sh"
load_env
# shellcheck source=scripts/lib/tls.sh
. "${SCRIPT_DIR}/lib/tls.sh"
# shellcheck source=scripts/lib/harbor.sh
. "${SCRIPT_DIR}/lib/harbor.sh"

require_cmd curl
require_cmd jq

: "${HARBOR_URL:?}"; : "${HARBOR_INFRA_PROJECT:?}"; : "${HARBOR_APP_PROJECT:?}"
: "${HARBOR_USERNAME:?}"
: "${HARBOR_PASSWORD:?set HARBOR_PASSWORD in .env (never passed on argv)}"

ROBOT_NAME="${HARBOR_ROBOT_NAME:-vks-cicd}"
OUT_FILE="${HARBOR_ROBOT_OUT:-secrets/harbor-robot.env}"

HARBOR_TMP="$(mktemp -d)"; trap 'rm -rf "$HARBOR_TMP"' EXIT
harbor_setup "$HARBOR_TMP"

# The two mirror projects must exist first (the robot is scoped to them).
ensure_project "$HARBOR_INFRA_PROJECT"
ensure_project "$HARBOR_APP_PROJECT"

# System-level robot (spans >1 project) with push+pull on each mirror project.
perm() { printf '{"kind":"project","namespace":"%s","access":[{"resource":"repository","action":"push"},{"resource":"repository","action":"pull"}]}' "$1"; }
payload="$(jq -nc \
  --arg name "$ROBOT_NAME" \
  --argjson perms "[$(perm "$HARBOR_INFRA_PROJECT"),$(perm "$HARBOR_APP_PROJECT")]" \
  '{name:$name, duration:-1, level:"system", description:"vks-airgap-cicd CI push/pull", permissions:$perms}')"

log_info "creating Harbor robot '$ROBOT_NAME' (push+pull on '$HARBOR_INFRA_PROJECT' + '$HARBOR_APP_PROJECT')"
resp="$(harbor_api_body POST robots "$payload")"

secret="$(printf '%s' "$resp" | jq -r '.secret // empty')"
rname="$(printf '%s' "$resp" | jq -r '.name // empty')"
if [ -z "$secret" ] || [ -z "$rname" ]; then
  # Never echo the raw response (could carry sensitive data); surface only the error message.
  msg="$(printf '%s' "$resp" | jq -r '(.errors[0].message // .message // "unknown error")' 2>/dev/null || echo 'unparseable response')"
  case "$msg" in
    *conflict*|*exists*|*already*) die "robot '$ROBOT_NAME' already exists — delete it in Harbor (Administration → Robot Accounts) to regenerate, or reuse the secret you saved earlier." ;;
    *) die "failed to create robot '$ROBOT_NAME': $msg" ;;
  esac
fi

# Write the credentials to a gitignored 0600 file. Single-quote both values: the robot name is
# `robot$<name>` and the secret can contain shell metacharacters — a double-quoted .env line
# would mis-expand `$<name>`. Copy these two lines into .env (replacing the admin creds).
mkdir -p "$(dirname "$OUT_FILE")"
( umask 077; {
    printf "# Harbor robot account for CI (generated by scripts/22-harbor-robot.sh). Copy into .env.\n"
    printf "HARBOR_USERNAME='%s'\n" "$rname"
    printf "HARBOR_PASSWORD='%s'\n" "$secret"
  } > "$OUT_FILE" )

log_info "robot account '$rname' created."
log_info "credentials written to $OUT_FILE (mode 0600, gitignored) — copy HARBOR_USERNAME/HARBOR_PASSWORD from it into .env."
log_warn "the secret is shown only once by Harbor; keep $OUT_FILE safe (or delete it after copying into .env)."
