#!/usr/bin/env bash
# scripts/argocd-ca-from-cluster.sh — get the ArgoCD Supervisor Service's TLS certificate from the
# Supervisor's API instead of trusting it on first use off the wire (B486).
#
# WHY: `make fetch-argocd-ca` reads the certificate from the TLS handshake. That is trust-on-first-use,
# so it asks for consent, and a non-interactive walk cannot give it. On VKS the default ArgoCD
# certificate is a SELF-SIGNED LEAF (CA:FALSE) generated by argocd-server (upstream util/settings,
# v3.0.19) and stored in a Secret. Reading it over the AUTHENTICATED Supervisor API is not TOFU.
#
# 🔴 THE GRANT THIS COSTS. `argocd-secret` also holds the admin password, server.secretkey and tls.key,
# and Kubernetes RBAC has no field-level read. Only .data.tls.crt is extracted here, but the identity
# running this can read all of it: an ADMIN-level grant. That is scenario-1 (the Supervisor operator);
# a tenant uses `make fetch-argocd-ca` and confirms the fingerprint with the platform team.
#
# VERIFIED, NOT ASSUMED: the leaf read from the Secret must be BYTE-IDENTICAL (SHA-256) to the leaf
# ArgoCD serves. Anything else is refused and the output file is not touched.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/os.sh
. "${SCRIPT_DIR}/lib/os.sh"

load_env
require_cmd kubectl
require_cmd openssl

if [ -z "${1:-}" ]; then
  # shellcheck disable=SC2016  # a Makefile reference shown to a human; it must NOT expand
  printf 'usage: argocd-ca-from-cluster.sh <out-file>   (the Makefile passes %s)\n' '$(ARGOCD_CA_FILE)' >&2
  exit 64
fi
OUT="$1"
: "${ARGOCD_NAMESPACE:?set ARGOCD_NAMESPACE in .env -- the vSphere Namespace the ArgoCD Service runs in}"
_addr="${ARGOCD_SERVER:-${ARGOCD_LB_IP:-}}"
[ -n "$_addr" ] || die "set ARGOCD_SERVER (make argocd-address publishes it) -- needed to compare with what ArgoCD serves"
_addr="${_addr#https://}"; _addr="${_addr%%/*}"
case "$_addr" in *:*) _host="${_addr%%:*}"; _port="${_addr##*:}" ;; *) _host="$_addr"; _port=443 ;; esac

SUP="$(supervisor_kubeconfig || printf '%s' "${REPO_ROOT}/secrets/supervisor.kubeconfig")"
[ -f "$SUP" ] || { supervisor_kubeconfig_hint >&2; die "no Supervisor kubeconfig — see the search order above"; }

t="$(mktemp)"; w="$(mktemp)"; e="$(mktemp)"; trap 'rm -f "$t" "$w" "$e"' EXIT

# argocd-server-tls, when present, OVERRIDES the generated certificate (upstream); otherwise argocd-secret.
_src=""
for s in argocd-server-tls argocd-secret; do
  _rc=0
  kubectl --kubeconfig "$SUP" --request-timeout="${KUBECTL_REQUEST_TIMEOUT:-15s}" -n "$ARGOCD_NAMESPACE" \
    get secret "$s" -o jsonpath='{.data.tls\.crt}' > "$w" 2>"$e" || _rc=$?
  if [ "$_rc" -ne 0 ]; then
    if grep -q 'NotFound' "$e"; then continue; fi
    _cls="$(classify_kube_failure "$e")"
    sed 's/^/    /' "$e" >&2
    die "could not read ${ARGOCD_NAMESPACE}/${s} (${_cls}). Nothing was learned about the certificate;
  '${OUT}' was NOT touched. If the credentials expired: make vks-login"
  fi
  if [ -s "$w" ]; then _src="$s"; break; fi
done
[ -n "$_src" ] || die "neither argocd-server-tls nor argocd-secret in ${ARGOCD_NAMESPACE} carries .data.tls.crt.
  '${OUT}' was NOT touched. Use 'make fetch-argocd-ca' (reads the served certificate) instead."
base64 -d < "$w" > "$t" 2>/dev/null || die "${ARGOCD_NAMESPACE}/${_src} tls.crt is not base64. '${OUT}' was NOT touched."
openssl x509 -in "$t" -noout >/dev/null 2>&1 || die "${ARGOCD_NAMESPACE}/${_src} tls.crt is not a certificate. '${OUT}' was NOT touched."

# The served leaf. -servername argocd-server: the SNI a real client sends when it dials the name.
_wire_rc=0
timeout "${CA_VERIFY_TIMEOUT:-15}" openssl s_client -connect "${_host}:${_port}" -servername argocd-server \
  </dev/null 2>/dev/null | openssl x509 > "$w" 2>/dev/null || _wire_rc=$?
[ "$_wire_rc" -eq 0 ] && [ -s "$w" ] || die "${_host}:${_port} did not present a certificate, so the Secret's certificate could
  not be compared with it. That is a CONNECTION problem, not a verdict. '${OUT}' was NOT touched."
fp_secret="$(openssl x509 -in "$t" -noout -fingerprint -sha256 | cut -d= -f2)"
fp_wire="$(openssl x509 -in "$w" -noout -fingerprint -sha256 | cut -d= -f2)"
[ "$fp_secret" = "$fp_wire" ] || die "the certificate in ${ARGOCD_NAMESPACE}/${_src} is NOT the one ${_host}:${_port} serves.
    secret: ${fp_secret}
    served: ${fp_wire}
  Either ARGOCD_SERVER points at another ArgoCD, or the Service now serves a different certificate.
  '${OUT}' was NOT touched."

sans="$(openssl x509 -in "$t" -noout -ext subjectAltName 2>/dev/null | tail -n +2 | tr -d ' ')"
chmod 0644 "$t"
mv "$t" "$OUT"; trap 'rm -f "$w" "$e"' EXIT
log_info "wrote ${OUT}  (from ${ARGOCD_NAMESPACE}/${_src} over the authenticated Supervisor API)"
log_info "  SHA-256:  ${fp_secret}  == the certificate ${_host}:${_port} serves"
log_info "  names:    ${sans:-<none>}"
log_info "  It verifies ONLY a name in that list, never an IP. To use it: ARGOCD_SERVER=<one of those names>, resolving to ${_host}."
