#!/usr/bin/env bash
# scripts/argocd-ca-from-cluster.sh — get the ArgoCD Supervisor Service's TLS certificate from the
# Supervisor's API instead of trusting it on first use off the wire (B486).
#
# WHY: `make fetch-argocd-ca` reads the certificate from the TLS handshake. That is trust-on-first-use,
# so it asks for consent, and a non-interactive walk cannot give it. On VKS the default ArgoCD
# certificate is a SELF-SIGNED LEAF (CA:FALSE) generated by argocd-server (upstream util/settings,
# v3.0.19) and stored in a Secret. Reading it over the AUTHENTICATED Supervisor API is not TOFU.
#
# 🔴 THE GRANT THIS COSTS. `argocd-secret` also holds the admin password, server.secretkey and tls.key,
# and Kubernetes RBAC has no field-level read. Only .data.tls.crt is extracted here, but the identity
# running this can read all of it: an ADMIN-level grant. That is scenario-1 (the Supervisor operator);
# a tenant uses `make fetch-argocd-ca` and confirms the fingerprint with the platform team.
#
# VERIFIED, NOT ASSUMED: the leaf read from the Secret must be BYTE-IDENTICAL (SHA-256) to the leaf
# ArgoCD serves. Anything else is refused and the output file is not touched.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/os.sh
. "${SCRIPT_DIR}/lib/os.sh"
# shellcheck source=scripts/lib/tls.sh
. "${SCRIPT_DIR}/lib/tls.sh"   # ca_pin_verdict: ONE pin normaliser, shared with fetch-ca.sh

load_env
require_cmd kubectl
require_cmd openssl

if [ -z "${1:-}" ]; then
  # shellcheck disable=SC2016  # a Makefile reference shown to a human; it must NOT expand
  printf 'usage: argocd-ca-from-cluster.sh <out-file>   (the Makefile passes %s)\n' '$(ARGOCD_CA_FILE)' >&2
  exit 64
fi
OUT="$1"
: "${ARGOCD_NAMESPACE:?set ARGOCD_NAMESPACE in .env -- the vSphere Namespace the ArgoCD Service runs in}"
_addr="${ARGOCD_SERVER:-${ARGOCD_LB_IP:-}}"
[ -n "$_addr" ] || die "set ARGOCD_SERVER (make argocd-address publishes it) -- needed to compare with what ArgoCD serves"
_addr="${_addr#https://}"; _addr="${_addr%%/*}"
case "$_addr" in *:*) _host="${_addr%%:*}"; _port="${_addr##*:}" ;; *) _host="$_addr"; _port=443 ;; esac
# SNI = the name a real client dials (70-configure-argocd.sh and lib/tls.sh do the same). An IP sends
# no SNI of its own, so use the default certificate's bare name -- what the CLI sends once it dials it.
case "$(ca_addr_kind "$_host")" in ip) _sni=argocd-server ;; *) _sni="$_host" ;; esac

SUP="$(supervisor_kubeconfig || printf '%s' "${REPO_ROOT}/secrets/supervisor.kubeconfig")"
[ -f "$SUP" ] || { supervisor_kubeconfig_hint >&2; die "no Supervisor kubeconfig — see the search order above"; }

t="$(mktemp)"; w="$(mktemp)"; e="$(mktemp)"; trap 'rm -f "$t" "$w" "$e"' EXIT

# argocd-server-tls, when present, OVERRIDES the generated certificate (upstream); otherwise argocd-secret.
_src=""
for s in argocd-server-tls argocd-secret; do
  _rc=0
  kubectl --kubeconfig "$SUP" --request-timeout="${KUBECTL_REQUEST_TIMEOUT:-15s}" -n "$ARGOCD_NAMESPACE" \
    get secret "$s" -o jsonpath='{.data.tls\.crt}' > "$w" 2>"$e" || _rc=$?
  if [ "$_rc" -ne 0 ]; then
    if grep -q 'NotFound' "$e"; then continue; fi
    _cls="$(classify_kube_failure "$e")"
    sed 's/^/    /' "$e" >&2
    die "could not read ${ARGOCD_NAMESPACE}/${s} (${_cls}). Nothing was learned about the certificate;
  '${OUT}' was NOT touched. If the credentials expired: make vks-login"
  fi
  if [ -s "$w" ]; then _src="$s"; break; fi
done
if [ -z "$_src" ]; then
  # A GET on a secret in a namespace that does not exist ALSO says NotFound, so "no certificate here"
  # and "wrong namespace" read the same. Tell them apart before steering anyone to trust-on-first-use.
  _nrc=0
  kubectl --kubeconfig "$SUP" --request-timeout="${KUBECTL_REQUEST_TIMEOUT:-15s}" get ns "$ARGOCD_NAMESPACE" \
    >/dev/null 2>"$e" || _nrc=$?
  if [ "$_nrc" -ne 0 ] && grep -q 'NotFound' "$e"; then
    die "namespace '${ARGOCD_NAMESPACE}' does not exist on this Supervisor — check ARGOCD_NAMESPACE in .env.
  '${OUT}' was NOT touched."
  fi
fi
[ -n "$_src" ] || die "neither argocd-server-tls nor argocd-secret in ${ARGOCD_NAMESPACE} carries .data.tls.crt.
  '${OUT}' was NOT touched. Use 'make fetch-argocd-ca' (reads the served certificate) instead."
base64 -d < "$w" > "$t" 2>/dev/null || die "${ARGOCD_NAMESPACE}/${_src} tls.crt is not base64. '${OUT}' was NOT touched."
openssl x509 -in "$t" -noout >/dev/null 2>&1 || die "${ARGOCD_NAMESPACE}/${_src} tls.crt is not a certificate. '${OUT}' was NOT touched."

# The served leaf, with the SNI chosen above.
_wire_rc=0
timeout "${CA_VERIFY_TIMEOUT:-15}" openssl s_client -connect "${_host}:${_port}" -servername "$_sni" \
  </dev/null 2>/dev/null | openssl x509 > "$w" 2>/dev/null || _wire_rc=$?
[ "$_wire_rc" -eq 0 ] && [ -s "$w" ] || die "${_host}:${_port} did not present a certificate, so the Secret's certificate could
  not be compared with it. That is a CONNECTION problem, not a verdict. '${OUT}' was NOT touched."
fp_secret="$(openssl x509 -in "$t" -noout -fingerprint -sha256 | cut -d= -f2)"
fp_wire="$(openssl x509 -in "$w" -noout -fingerprint -sha256 | cut -d= -f2)"
[ "$fp_secret" = "$fp_wire" ] || die "the certificate in ${ARGOCD_NAMESPACE}/${_src} is NOT the one ${_host}:${_port} serves.
    secret: ${fp_secret}
    served: ${fp_wire}
  Either ARGOCD_SERVER points at another ArgoCD, or the Service now serves a different certificate.
  '${OUT}' was NOT touched."

# An out-of-band pin, when the operator has one, must agree too (the same contract fetch-ca.sh enforces).
_pv=0; ca_pin_verdict "$t" "${ARGOCD_CA_SHA256:-}" || _pv=$?
case "$_pv" in
  0|3) ;;
  4) die "ARGOCD_CA_SHA256 is set but is not a SHA-256 digest (64 hex, colons optional). '${OUT}' was NOT touched." ;;
  *) die "the certificate does NOT match ARGOCD_CA_SHA256.
    pinned:   ${ARGOCD_CA_SHA256}
    served:   ${fp_secret}
  '${OUT}' was NOT touched." ;;
esac

sans="$(openssl x509 -in "$t" -noout -ext subjectAltName 2>/dev/null | tail -n +2 | tr -d ' ')"
chmod 0644 "$t"
mv "$t" "$OUT"; trap 'rm -f "$w" "$e"' EXIT
log_info "wrote ${OUT}  (from ${ARGOCD_NAMESPACE}/${_src} over the authenticated Supervisor API)"
log_info "  SHA-256:  ${fp_secret}  == the certificate ${_host}:${_port} serves"
log_info "  names:    ${sans:-<none>}"
[ "$_pv" = 0 ] && log_info "  matches ARGOCD_CA_SHA256"
[ -n "${ARGOCD_CA_FILE:-}" ] || log_info "  set it in .env, e.g.  ARGOCD_CA_FILE=${OUT}"
if [ "$(ca_addr_kind "$_host")" = ip ]; then
  log_warn "  ARGOCD_SERVER is the IP ${_host}, and this certificate verifies ONLY the names above."
  log_warn "  Until ARGOCD_SERVER is one of those names, setting ARGOCD_CA_FILE makes every verifying"
  log_warn "  argocd call fail on the name. Map one in /etc/hosts to ${_host} and set ARGOCD_SERVER to it first."
else
  log_info "  It verifies ONLY a name in that list, never an IP."
fi
