#!/usr/bin/env bash
# ci-tier: fast
# Offline RED/GREEN for check-env-coverage's PASS-2b SECTION-SCOPED window (B716 stage 1).
#
# THE DEFECT PASS 2 HAS. Its awk resets the comment block only on a NON-COMMENT line, and
# `.env.example` is an unbroken run of `#` lines — so a variable's "own block" absorbs its
# NEIGHBOURS'. Measured on the real file: 241 slots, 155 (64%) with a window >20 lines, max **247**,
# and it flags **0**. The gate's own comment says a wider window "would pick up a NEIGHBOURING
# block's marker and the gate would never fire".
#
# ⚠️ WHY THE OBVIOUS FIX IS NOT THE ONE UNDER TEST. Also resetting on a slot line gives 57 flags,
# but MEASURED **34 of those (60%) are documented by a GROUP HEADER that names them** — this file's
# dominant idiom is one header above a RUN of slots. Case 2 below is the assertion that makes that
# design impossible to ship by accident.
#
# ⚠️ FIXTURES, NOT THE LIVE FILE. Keying a proof on real variable names rots on the next
# documentation edit — which is exactly how "VKS_PASSWORD must FAIL" would have rotted: that row's
# prescribed RED-proof target is in fact DOCUMENTED (its slot line carries `<SET-IN-.env>`), so
# pinning its RED would have enshrined a false positive as the gate's correctness criterion.
#
# The fixture is PADDED to a realistic size on purpose: PASS 1 hard-exits below 80 scripts and
# PASS 2b's own floor is 200 slots. Both floors stay unconditional — a test that has to weaken a
# floor to run is testing a different gate.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
mkdir -p "$T/scripts/lib"

# 85 trivial flow scripts: enough to clear PASS 1's floor, reading no variables so PASS 1 is silent.
# ⚠️ DO NOT copy the real lib/os.sh in: PASS 1 would then flag the ~21 variables it reads that this
# fixture does not document, the gate exits 1, and every PASS-2b assertion below reads 0 — three
# failures with one cause, none of them the product. Measured while writing this file.
i=0; while [ "$i" -lt 85 ]; do printf '#!/usr/bin/env bash\ntrue\n' > "$T/scripts/$(printf '%02d' "$i")-pad.sh"; i=$((i+1)); done

mkfixture() {  # mkfixture <extra-lines-file>
  : > "$T/.env.example"
  # ⚠️ THE PAD COUNT IS DERIVED FROM THE GATE, NOT HARDCODED. It was a literal 200 matching a
  # literal 200 floor; raising the floor to 225 for the D2 change silently pushed the fixture UNDER
  # it, the gate exited 1, and the "flags are REPORT-ONLY (rc stays 0)" case failed for a reason
  # with nothing to do with report-only-ness. MEASURED: 12 passed, 1 failed. Two literals, one
  # invariant -- exactly the drift this repo gates elsewhere. Fail LOUD if the grep stops matching,
  # rather than silently padding to a wrong size.
  _floor=$(sed -n 's/.*pass2_examined" -lt \([0-9][0-9]*\).*/\1/p' "$SCRIPT_DIR/check-env-coverage.sh" | head -1)
  case "${_floor:-}" in ''|*[!0-9]*) printf 'FATAL: cannot read the PASS 2b floor from the gate\n' >&2; exit 1 ;; esac
  _pads=$((_floor + 15))
  n=0; while [ "$n" -lt "$_pads" ]; do
    printf '# how: generated by the installer\n# PAD_%03d=1\n' "$n" >> "$T/.env.example"; n=$((n+1))
  done
  # ⚠️ A MARKER-FREE SEPARATOR IS LOAD-BEARING. Without it the last PAD slot and the first fixture
  # slot are CONTIGUOUS, so they form one RUN whose head is a padded `# how:` block — and every case
  # below silently passes for a reason the case is not testing. Measured: 0 flagged where 1 was
  # expected. A comment line that is not a slot breaks the run, which is exactly the semantics
  # under test.
  printf '#\n# ---- fixture ----\n#\n' >> "$T/.env.example"
  cat "$1" >> "$T/.env.example"
}

run() { REPO_ROOT="$T" bash "$SCRIPT_DIR/check-env-coverage.sh" 2>&1 | tr '\n' ' '; }
# ⚠️ SCOPED TO THE REPORT-ONLY LINE. A bare grep over the whole output cannot tell WHICH pass named
# a variable, so a case could report ok on an ENFORCING-pass error. Harmless only by coincidence
# today; at stage 3 (2b enforcing) both coincidences evaporate.
has()  { printf '%s' "$2" | sed -n 's/.*no acquisition path stated[^:]*://p' | grep -c "$1"; }

p=0; f=0
ck(){ if [ "$2" = "$3" ]; then p=$((p+1)); printf '  ok    %s\n' "$1"
      else f=$((f+1)); printf '  FAIL  %s (got=%s want=%s)\n' "$1" "$2" "$3"; fi; }

# ---- 1. THE RED THAT DOES NOT EXIST TODAY: a slot that inherits a NEIGHBOUR's marker -------------
# The run is BROKEN between them by a marker-free comment, so BARE_SLOT cannot inherit the header.
# (If they were contiguous, BARE_SLOT would be covered -- and correctly so; that is case 2.)
#
# ⚠️ EVERY WORD INSIDE THE HEREDOC IS FIXTURE DATA. Two drafts of this case failed because the
# explanatory prose I wrote into it contained a MARKER: first "...nothing about HOW to obtain...",
# then a note whose own text quoted the marker word. Keep fixture prose semantically empty and put
# the explanation OUT HERE. Verified below by grepping the rendered fixture.
cat > "$T/x" <<'EOF'
# how: run `make something` to get this
# NEIGHBOUR_DOC=1
#
# (unrelated prose)
# BARE_SLOT=2
EOF
mkfixture "$T/x"; out="$(run)"
# THE FIXTURE'S OWN INSTRUMENT CHECK: prove the block really is marker-free before believing a
# verdict about it. A fixture that accidentally documents its own variable tests nothing.
_blk="$(sed -n '/^# (unrelated prose)$/p' "$T/.env.example" | tr '[:upper:]' '[:lower:]')"
ck "fixture prose is marker-FREE (instrument)" \
   "$(printf '%s' "$_blk" | grep -cE 'how|acquire|auto|discover|generated|choose|you set|toggle|runtime|password|request|reserved|default|set[- ]in')" "0"
ck "neighbour-inherited slot is FLAGGED"   "$(has 'BARE_SLOT' "$out")" "1"
ck "  ...and the documented one is NOT"     "$(has 'NEIGHBOUR_DOC' "$out")" "0"

# ---- 1b. D2: A PROSE LINE THAT LOOKS LIKE A SLOT IS NOT ONE -------------------------------------
# THE SUITE WAS STRUCTURALLY BLIND TO THIS AND AN IDEA ROUND SAID SO: no fixture slot had trailing
# content, which is exactly why the REFUTED syntax discriminator ("a real slot has nothing after the
# =") sailed through at 13/13 GREEN while silently dropping 23 REAL variables -- VKS_PASSWORD and
# VCENTER_PASSWORD among them -- from the denominator.
#
# `# PROSE_VAR=0 disables the thing.` is PROSE. It must (a) not be counted as a variable, and
# (b) NOT WALL the real slot below it: before D2 it did both, so the real slot lost its `# how:`
# and the phantom was reported instead of the variable. Both halves are asserted -- fixing only the
# enumeration was my first attempt and it left 5 of 7 expected removals undone.
cat > "$T/x" <<'EOF'
# how: obtained from the platform team
# PROSE_VAR=0 disables the thing entirely. Set it only when you must.
# PROSE_VAR=1
EOF
mkfixture "$T/x"; out="$(run)"
ck "prose-shaped slot does not WALL the real one" "$(has 'PROSE_VAR' "$out")" "0"

# ---- 1c. D2 must NOT demote a REAL slot that carries trailing content ----------------------------
# The three shapes measured in the live file, all REAL slots: a trailing comment, a value with
# spaces, and a `<SET-IN-.env -- ...>` placeholder. Each is marker-free on purpose, so each MUST be
# flagged -- if D2 wrongly demoted them to prose they would vanish from the denominator instead, and
# the count would read 0. This case fails in BOTH directions.
cat > "$T/x" <<'EOF'
#
# (no acquisition prose here)
# TRAILING_CMT=./secrets/x.crt   # a note after the value
#
# (no acquisition prose here)
# SPACED_VAL=0 1 2 4 8
EOF
mkfixture "$T/x"; out="$(run)"
ck "real slot with a TRAILING COMMENT is still counted" "$(has 'TRAILING_CMT' "$out")" "1"
ck "real slot with a SPACED VALUE is still counted"     "$(has 'SPACED_VAL' "$out")" "1"

# ---- 2. THE ASSERTION THAT FORBIDS THE 57-FALSE-RED DESIGN: a GROUP HEADER covers its whole run --
cat > "$T/x" <<'EOF'
# how: all three of these are set by the platform team
# GROUPED_A=1
# GROUPED_B=2
# GROUPED_C=3
EOF
mkfixture "$T/x"; out="$(run)"
ck "group header covers the WHOLE run"      "$(has 'GROUPED_' "$out")" "0"

# ---- 3. BOUNDING: the window must NOT reach a marker two groups up -------------------------------
cat > "$T/x" <<'EOF'
# how: this marker belongs to the FIRST group only
# FIRST_GROUP=1
#
# (prose with no marker at all, belonging to the second group)
# SECOND_GROUP=2
EOF
mkfixture "$T/x"; out="$(run)"
ck "a marker two groups up does NOT carry"  "$(has 'SECOND_GROUP' "$out")" "1"

# ---- 4. THE SLOT LINE ITSELF is part of the window (this file's own `<SET-IN-.env>` idiom) --------
cat > "$T/x" <<'EOF'
# SETIN_VAR=<SET-IN-.env>
#
# (prose that states nothing)
# NOTHING_VAR=1
EOF
mkfixture "$T/x"; out="$(run)"
ck "<SET-IN-.env> on the slot line PASSES"  "$(has 'SETIN_VAR' "$out")" "0"
ck "a bare slot with nothing FAILS"         "$(has 'NOTHING_VAR' "$out")" "1"

# ---- 5. THE DENOMINATOR, reconciled a SECOND way rather than self-reported ------------------------
independent=$(grep -cE '^#[[:space:]]*[A-Z][A-Z0-9_]{2,}=' "$T/.env.example")
# ⚠️ THIS LINE USED TO BE A TAUTOLOGY carrying the suite's most load-bearing label: it compared
# `flagged("<N> commented slot")` -- which by construction returns "" -- against the literal "".
# Proven un-failable by hardcoding the printed denominator to 999: the tautology reported ok while
# the line below it failed. The label now sits on the check that does the work.
ck "printed denominator == an INDEPENDENT count" \
   "$(printf '%s' "$out" | grep -oE '[0-9]+ commented slot' | head -1 | grep -oE '^[0-9]+')" "$independent"

# ---- 5b. AN UPPERCASE MARKER MUST STILL COUNT. Without this case, dropping tolower() from the two
#          upward loops leaves the suite 10/10 GREEN while the real .env.example goes 21 -> 32
#          flagged (11 false REDs) -- because every marker in every other fixture is lowercase, so
#          nothing here can distinguish a lowered window from a raw one. Measured by the round.
cat > "$T/x" <<'EOF'
# HOW: run `make something` to get this
# UPPER_MARKER_VAR=1
EOF
mkfixture "$T/x"; out="$(run)"
ck "an UPPERCASE marker still covers its slot" "$(has 'UPPER_MARKER_VAR' "$out")" "0"

# ---- 6. REPORT-ONLY: flags must NOT fail the build (stage 1 of 3) --------------------------------
REPO_ROOT="$T" bash "$SCRIPT_DIR/check-env-coverage.sh" >/dev/null 2>&1; rc=$?
ck "flags are REPORT-ONLY (rc stays 0)"     "$rc" "0"

# ---- 7. THE 2b FLOOR IS THE ONE NEW WAY THIS GATE CAN FAIL, and it had no RED-proof: setting its
#         threshold to 0 left the suite green.
# ⚠️ THE FIXTURE SIZE IS LOAD-BEARING. My first attempt used 20 slots — below BOTH floors, so rc=1
# came from the ENFORCING pass's floor (150) and the case could not tell which fired: disabling the
# 2b floor still left it green. 175 sits ABOVE 150 and BELOW 200, so ONLY 2b's floor can fire, and
# the message is asserted rather than the bare rc.
: > "$T/.env.example"
n=0; while [ "$n" -lt 175 ]; do printf '# how: x\n# TINY_%03d=1\n' "$n" >> "$T/.env.example"; n=$((n+1)); done
out_floor="$(REPO_ROOT="$T" bash "$SCRIPT_DIR/check-env-coverage.sh" 2>&1)"; rc_floor=$?
ck "a fixture below the 2b floor fails"      "$rc_floor" "1"
ck "  ...and it is 2b's floor that fired"    "$(printf '%s' "$out_floor" | grep -c 'PASS 2b: only 175 slots')" "1"
ck "  ...NOT the enforcing pass's floor"     "$(printf '%s' "$out_floor" | grep -c 'ENFORCING pass went blind')" "0"

printf '\n  %s passed, %s failed\n' "$p" "$f" >/dev/null   # (tally printed below)

printf '\n  %s passed, %s failed\n' "$p" "$f"
[ "$f" -eq 0 ] || exit 1
